name: S3 Deploy Actions

on:
  push:

jobs:
  build-deploy:
    uses: Vis-Rodrigues/workflow-template/.github/workflows/deploy-s3-action.yml@main
    with:
      s3-bucket-name: 'fiap-hmv-react-bucket'
    secrets:
      aws-region: ${{ secrets.AWS_REGION }}
      aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
      aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
